### ISSUE TITLE
Upstreaming the patches to Erigon?

### ISSUE THREAD

**Issue by wbl** [wmitsuda/otterscan#177]
Are these patches to Erigon something that will be upstreamed? I've been trying to set up an explorer for a local testnet and otterscan looks interesting, but replacing one binary from another project sounds like pain and sadness.

**Comment by wmitsuda** [comment]
Eventually... I'm still trying to find the right balance between upstreaming and keeping everything all here because making changes in a fork is quicker than submitting a PR to another repo which is shared with other stuff.

Maybe we can break down your pain by addressing more specific issues? Could you contribute to the discussion on issue #20 ?

**Comment by wbl** [comment]
Conceptually the the interface between the block explorer and node should be relatively fixed. If features are constantly requiring changes I think that's a sign that functionality is on the wrong side. As a result it should be possible to upstream, even if occasionally interface changes are made. Will comment on #20

**Comment by wmitsuda** [comment]
Will close this issue, let's continue the discussion on #20
